# Generated by Django 5.2.17 on 2026-09-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('customer_type', models.CharField(choices=[('CLINIC', 'Clinic'), ('HOSPITAL', 'Hospital'), ('PHARMACY', 'Pharmacy'), ('DISTRIBUTOR', 'Distributor'), ('INDIVIDUAL', 'Individual'), ('OTHER', 'Other')], default='INDIVIDUAL', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_profiles',
            },
        ),
    ]
