# Generated by Django 5.2.17 on 2026-09-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_customerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='barangay',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(blank=True, default='Philippines', max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='delivery_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='house_unit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='province',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
